# Generated by Django 2.2.6 on 2019-10-18 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('date_add', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('jeton', models.PositiveIntegerField()),
                ('prix', models.FloatField()),
                ('status', models.BooleanField()),
                ('date_add', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('video', models.URLField()),
                ('status', models.BooleanField()),
                ('date_add', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_categorie', to='videoapp.Categorie')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='User_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton', models.PositiveIntegerField()),
                ('jeton_restant', models.PositiveIntegerField()),
                ('status', models.BooleanField()),
                ('date_add', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_model', to='videoapp.Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_module', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_module',
                'verbose_name_plural': 'User_modules',
            },
        ),
    ]
