# Generated by Django 2.2.6 on 2019-10-18 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_auto_20191018_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_module',
            name='apikey',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user_module',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='videoapp.Module'),
        ),
        migrations.AlterField(
            model_name='user_module',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
