# Generated by Django 2.2.6 on 2019-10-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_auto_20191018_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(null=True, upload_to='images/module/'),
        ),
    ]
