# Generated by Django 2.2.6 on 2019-10-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0004_module_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_module',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_module',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user_module',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
